name: Build Firmware Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-avr:
    name: Build AVR Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install AVR Toolchain
        run: |
            sudo apt-get update
            sudo apt-get install -y gcc-avr avr-libc make

      - name: Build AVR Projects
        run: find . -name "Makefile" -execdir make \;
